import React from 'react';
import { X, Receipt, CheckCircle2, Circle, Ban, Send, Award, Truck, ShieldCheck } from 'lucide-react';

export default function PODetailModal({ isOpen, onClose, po }) {
  if (!isOpen || !po) return null;

  const getStatusColor = (status) => {
    switch (status) {
      case 'Approved': return 'text-indigo-600 bg-indigo-50 border-indigo-200';
      case 'Pending': return 'text-amber-600 bg-amber-50 border-amber-200';
      case 'Fulfilled': return 'text-emerald-600 bg-emerald-50 border-emerald-200';
      case 'Rejected': return 'text-rose-600 bg-rose-50 border-rose-200';
      default: return 'text-slate-600 bg-slate-50 border-slate-200';
    }
  };

  const getUrgencyBadge = (urgency) => {
    switch (urgency) {
      case 'High':
        return <span className="text-xs text-rose-600 font-bold bg-rose-50 px-2 py-0.5 rounded border border-rose-100">HIGH</span>;
      case 'Medium':
        return <span className="text-xs text-amber-600 font-bold bg-amber-50 px-2 py-0.5 rounded border border-amber-100">MEDIUM</span>;
      default:
        return <span className="text-xs text-slate-500 font-medium bg-slate-100 px-2 py-0.5 rounded">LOW</span>;
    }
  };

  // Timeline representation
  const timelineSteps = [
    { label: 'PO Created', desc: `Draft generated by ${po.requester.split(' ')[0]}`, icon: Send, done: true },
    { 
      label: 'Supervisor Approval', 
      desc: po.status === 'Rejected' ? 'Authorization declined' : po.status === 'Pending' ? 'Currently routing for signature' : 'Authorized by Management', 
      icon: ShieldCheck, 
      done: po.status === 'Approved' || po.status === 'Fulfilled',
      failed: po.status === 'Rejected',
      active: po.status === 'Pending'
    },
    { 
      label: 'Contract Awarded', 
      desc: po.status === 'Fulfilled' ? 'Supplier confirmed dispatch' : po.status === 'Approved' ? 'Awaiting supplier confirmation' : 'Pending prior routing', 
      icon: Award, 
      done: po.status === 'Fulfilled',
      active: po.status === 'Approved'
    },
    { 
      label: 'Delivery & Reconciliation', 
      desc: po.status === 'Fulfilled' ? 'Goods received and QA passed' : 'Pending delivery', 
      icon: Truck, 
      done: po.status === 'Fulfilled' 
    }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm transition-opacity duration-300" onClick={onClose} />
      
      {/* Modal Dialog */}
      <div className="relative bg-white rounded-2xl shadow-xl border border-slate-200 max-w-2xl w-full overflow-hidden animate-slide-in">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-indigo-50 text-indigo-600 rounded-lg">
              <Receipt className="h-5 w-5" />
            </div>
            <div>
              <h3 className="text-base font-heading font-bold text-slate-800 m-0">Purchase Order Details</h3>
              <span className="text-[11px] text-slate-400 font-bold tracking-wide">{po.id}</span>
            </div>
          </div>
          <button 
            onClick={onClose} 
            className="text-slate-400 hover:text-slate-600 transition-colors p-1 hover:bg-slate-100 rounded-lg"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6 max-h-[80vh] overflow-y-auto scrollbar-none">
          {/* Summary Row */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 bg-slate-50/75 border border-slate-200/50 rounded-2xl p-4">
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Financial Value</span>
              <span className="block text-xl font-extrabold text-slate-800 mt-0.5">
                ${po.amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              </span>
            </div>
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Order Status</span>
              <div className="mt-1">
                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold border ${getStatusColor(po.status)}`}>
                  {po.status}
                </span>
              </div>
            </div>
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Urgency Code</span>
              <div className="mt-1">
                {getUrgencyBadge(po.urgency)}
              </div>
            </div>
          </div>

          {/* Details Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Item / Scope</span>
              <span className="block text-sm font-semibold text-slate-800 mt-1">{po.subject}</span>
            </div>
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Supplier / Vendor</span>
              <span className="block text-sm font-semibold text-slate-800 mt-1">{po.vendor}</span>
            </div>
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Initiated By</span>
              <span className="block text-sm font-semibold text-slate-800 mt-1">{po.requester}</span>
            </div>
            <div>
              <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wider">Routing Date</span>
              <span className="block text-sm font-semibold text-slate-800 mt-1">{po.date}</span>
            </div>
          </div>

          {/* Flow Tracker */}
          <div className="border-t border-slate-100 pt-6">
            <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider mb-4">Lifecycle Timeline</h4>
            <div className="relative pl-6 space-y-6 before:absolute before:left-2.5 before:top-2 before:bottom-2 before:w-0.5 before:bg-slate-100">
              {timelineSteps.map((step, idx) => {
                const Icon = step.icon;
                return (
                  <div key={idx} className="relative flex items-start gap-4">
                    {/* Circle Indicator */}
                    <span className={`absolute -left-6 top-1 h-5.5 w-5.5 rounded-full border-2 flex items-center justify-center bg-white z-10
                      ${step.done ? 'bg-emerald-50 border-emerald-500 text-emerald-600' : 
                        step.failed ? 'bg-rose-50 border-rose-500 text-rose-600' :
                        step.active ? 'bg-indigo-50 border-indigo-600 text-indigo-600 animate-pulse' :
                        'bg-white border-slate-200 text-slate-300'}
                    `}>
                      {step.done ? (
                        <CheckCircle2 className="h-3.5 w-3.5 fill-emerald-50 text-emerald-600" />
                      ) : step.failed ? (
                        <Ban className="h-3.5 w-3.5 text-rose-600" />
                      ) : (
                        <Icon className="h-3 w-3" />
                      )}
                    </span>
                    
                    {/* Step Description */}
                    <div className="flex-1 min-w-0">
                      <span className={`block text-xs font-bold ${step.active ? 'text-indigo-600' : step.done ? 'text-slate-800' : 'text-slate-400'}`}>
                        {step.label}
                      </span>
                      <span className="block text-[11px] text-slate-500 mt-0.5 leading-snug">{step.desc}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 flex items-center justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 text-xs font-bold text-slate-600 hover:text-slate-800 bg-white border border-slate-200 hover:bg-slate-50 rounded-xl transition-colors shadow-sm"
          >
            Close Details
          </button>
        </div>
      </div>
    </div>
  );
}
